// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Fog_Of_War","status":true,"description":"This plugin provides a complete fog of war system.","parameters":{"Enabled":"true","Fog Opacity":"0.75","Fade Speed":"0.1","Map Hidden":"true","Gradient Vision":"true","Strict Diagonals":"true","Player Vision":"true","Player Vision Range":"5","Player Vision Type":"3","Player Flying Vision":"false","Player Vision Brightness":"1","Origin Vision Range":"3","Origin Vision Type":"1","Origin Flying Vision":"false","Origin Vision Brightness":"1","Forest RegionId":"1","Hill RegionId":"2","Mountain / Wall RegionId":"3","Blocker RegionId":"4","Dark RegionId":"5","Watchtower RegionId":"6","Watchtower Modifier":"1"}}
];
